import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { unstable_ViewTransition as ViewTransition } from "react";
import RotaryMenu from "@/components/Home/RotaryMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <RotaryMenu />
        </nav>

        <main className="to-background from-foreground/20 bg-gradient-to-b">
          <ViewTransition>{children}</ViewTransition>
        </main>
      </body>
    </html>
  );
}
